services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SDkgjkdnsi$3sfg2$sdnvjd$!sczxcasdSf
      MYSQL_DATABASE: keraseh_bot
      MYSQL_USER: kerasehBot
      MYSQL_PASSWORD: GdgaxSnX!si$3sfg2$sSX321jd$!sces21xSf
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  mysql_data:
