services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SDkgjkdnsi$3sfg2$sdnvjd$!sczxcasdSf
      MYSQL_DATABASE: keraseh_bot
      MYSQL_USER: kerasehBot
      MYSQL_PASSWORD: GdgaxSnX!si$3sfg2$sSX321jd$!sces21xSf
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8002:8000"

  nginx:
    image: nginx:latest
    restart: always
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  mysql_data: